package net.clansau.clans.fishing.enums;

public enum FishNames {

    GUMMY_SHARK, SNAPPER, SWORDFISH, TROUT,
    TUNA, BARRACUDA, SALMON, LOBSTER, CATFISH,
    GREAT_WHITE_SHARK, JELLYFISH, OCTOPUS, MARLIN,
    DOLPHIN, ANGLER_FISH, CARP, BREAM, STINGRAY,
    MACKEREL, FLATHEAD, BASS
}