name: ClansAU-Clans
author: Trae
main: net.clansau.clans.Clans
depend: [ ClansAU-Core, ClansAU-Champions ]
version: 1.0.0
commands:
  clan:
    aliases: [ c, f, g, fac, faction, gang ]
  clanchat:
    aliases: [ cc ]
  allychat:
    aliases: [ ac ]
  spawn: