package me.trae.clans.clan.enums;

public enum ClanProperty {

    TERRITORY, REQUESTS, MEMBERS, ALLIANCES, ENEMIES, PILLAGES, CREATED, LAST_ONLINE, LAST_TNTED, LAST_PILLAGED, ENERGY, FOUNDER, HOME, POINTS, ADMIN, SAFE
}